"""Integration coverage for creating agent profiles and using them in relay flows."""

from pathlib import Path
import threading

from fastapi.testclient import TestClient

from IM.app import create_app
from IM.domain.models import managed_workspace_root
from IM.repositories import NodeRepository, UserRepository

from .conftest import authorize, register_user

_WORKSPACE_PATH_SETTING = "/tmp/nano-test/workspace/test-agent"


def test_create_agent_lists_details_and_uses_new_node_binding_for_relay(
    tmp_path: Path,
) -> None:
    """Create an agent through HTTP, then use it in a real Web IM relay path."""
    app = create_app(db_path=tmp_path / "im.db")
    with TestClient(app) as client:
        users = UserRepository(app.state.connection)
        owner = register_user(client, username="owner", display_name="Owner")
        authorize(client, owner)
        human_user = users.create_user(username="alice", display_name="Alice")
        # feat-340-M18 R9-1: align the fixture's pre-seeded users row with the
        # canonical ``agent:<agent_id>`` username so the create-agent route's
        # ``ensure_agent_user`` step finds it instead of minting a duplicate.
        # (Without this, the random uuid generated by ``create_user`` for the
        # fixture would not match the deterministic username produced by the
        # service from the agent_id.)
        agent_user = users.create_user(
            username="agent:agent-new", display_name="Agent New"
        )
        app.state.connection.execute(
            "UPDATE users SET username = ? WHERE id = ?",
            (f"agent:{agent_user.id}", agent_user.id),
        )
        app.state.connection.execute(
            "UPDATE users SET owner_id = ? WHERE id IN (?, ?)",
            (owner.owner_id, human_user.id, agent_user.id),
        )
        app.state.connection.commit()
        NodeRepository(app.state.connection).upsert_node(
            node_id="node-1", node_name="MacBook"
        )

        with client.websocket_connect("/im/ws/gateway") as websocket:
            websocket.send_json(
                {
                    "type": "node.register",
                    "payload": {
                        "node_id": "node-1",
                        "node_name": "MacBook",
                        "version": "1.0.0",
                        "agents": [agent_user.id],
                        "capabilities": {"relay": True},
                    },
                }
            )
            assert websocket.receive_json()["type"] == "ack"

            creation_result: dict[str, object] = {}

            def _create_agent() -> None:
                creation_result["response"] = client.post(
                    "/im/v1/nodes/node-1/agents",
                    json={
                        "agent_id": agent_user.id,
                        "owner_id": owner.owner_id,
                        "display_name": "Agent New",
                        "description": "runtime-created helper",
                        "system_prompt": "You are Agent New.",
                        "skills": ["plan"],
                        "tool_allowlist": ["read"],
                        "group_reply_policy": "MENTION",
                        "default_model": "claude-sonnet-4",
                    },
                )

            creation_worker = threading.Thread(target=_create_agent)
            creation_worker.start()
            create_request = websocket.receive_json()
            assert create_request["type"] == "agent.create"
            request_id = create_request["payload"]["request_id"]
            assert create_request["payload"]["agent"] == {
                "agent_id": agent_user.id,
                "display_name": "Agent New",
                "description": "runtime-created helper",
                "system_prompt": "You are Agent New.",
                "skills": ["plan"],
                "tool_allowlist": ["read"],
                "group_reply_policy": "MENTION",
                "default_model": "claude-sonnet-4",
                "workspace_root": None,
            }
            websocket.send_json(
                {
                    "type": "agent.created",
                    "payload": {
                        "request_id": request_id,
                        "node_id": "node-1",
                        "agent": {
                            "agent_id": agent_user.id,
                            "display_name": "Agent New",
                            "description": "runtime-created helper",
                            "system_prompt": "You are Agent New.",
                            "skills": ["plan"],
                            "tool_allowlist": ["read"],
                            "group_reply_policy": "MENTION",
                            "default_model": "claude-sonnet-4",
                            "workspace_root": _WORKSPACE_PATH_SETTING,
                        },
                    },
                }
            )
            assert websocket.receive_json() == {
                "type": "ack",
                "payload": {
                    "message_type": "agent.created",
                    "request_id": request_id,
                    "node_id": "node-1",
                },
            }
            assert websocket.receive_json() == {
                "type": "config.sync",
                "payload": {"agent_id": agent_user.id, "profile_version": 1},
            }
            creation_worker.join(timeout=5)
            created = creation_result["response"]
            assert created.status_code == 201
            assert created.json()["agent_id"] == agent_user.id
            assert created.json()["node_id"] == "node-1"
            assert created.json()["workspace_root"] == _WORKSPACE_PATH_SETTING

            listed = client.get("/im/v1/agents")
            assert listed.status_code == 200
            # Use subset assertion: node_status is runtime-derived and may change.
            agent_row = listed.json()[0]
            assert {
                k: agent_row[k]
                for k in (
                    "agent_id",
                    "owner_id",
                    "node_id",
                    "display_name",
                    "description",
                    "profile_version",
                    "default_model",
                    "workspace_root",
                    "workspace_is_default",
                    "user_id",
                )
            } == {
                "agent_id": agent_user.id,
                "owner_id": owner.owner_id,
                "node_id": "node-1",
                "display_name": "Agent New",
                "description": "runtime-created helper",
                "profile_version": 1,
                "default_model": "claude-sonnet-4",
                "workspace_root": _WORKSPACE_PATH_SETTING,
                "workspace_is_default": False,
                "user_id": agent_user.id,
            }

            detail = client.get(f"/im/v1/agents/{agent_user.id}/config")
            assert detail.status_code == 200
            assert detail.json()["node_id"] == "node-1"
            assert detail.json()["group_reply_policy"] == "MENTION"
            assert detail.json()["workspace_root"] == _WORKSPACE_PATH_SETTING

            conversation = client.post(
                "/im/v1/conversations",
                json={
                    "title": "new agent thread",
                    "participant_ids": [human_user.id, agent_user.id],
                },
            )
            assert conversation.status_code == 201

            created_message = client.post(
                f"/im/v1/conversations/{conversation.json()['id']}/messages",
                headers={"Idempotency-Key": "idem-agent-create"},
                json={
                    "sender_user_id": human_user.id,
                    "content": "hello new agent",
                    "target_node_id": "node-1",
                },
            )
            assert created_message.status_code == 201
            live_read_request = websocket.receive_json()
            assert live_read_request["type"] == "agent.config.get"
            websocket.send_json(
                {
                    "type": "agent.config",
                    "payload": {
                        "request_id": live_read_request["payload"]["request_id"],
                        "agent_id": agent_user.id,
                        "agent": None,
                    },
                }
            )
            next_frame = websocket.receive_json()
            if next_frame["type"] == "ack":
                assert next_frame == {
                    "type": "ack",
                    "payload": {
                        "message_type": "agent.config",
                        "request_id": live_read_request["payload"]["request_id"],
                        "agent_id": agent_user.id,
                    },
                }
                relay_frame = websocket.receive_json()
            else:
                relay_frame = next_frame

        assert relay_frame["type"] == "relay.message"
        assert relay_frame["payload"]["relay_task_id"]
        assert relay_frame["payload"]["idempotency_key"] == "idem-agent-create"
        assert relay_frame["payload"]["conversation_id"] == conversation.json()["id"]
        assert relay_frame["payload"]["agent_id"] == agent_user.id
        assert relay_frame["payload"]["message"]["id"] == created_message.json()["id"]
        assert relay_frame["payload"]["message"]["sender_user_id"] == human_user.id
        assert relay_frame["payload"]["message"]["content"] == "hello new agent"
        assert relay_frame["payload"]["message"]["attachments"] == []
        assert relay_frame["payload"]["message"]["id"] == created_message.json()["id"]
        assert (
            relay_frame["payload"]["message"]["conversation_id"]
            == conversation.json()["id"]
        )
        assert relay_frame["payload"]["message"]["sender_type"] == "user"
        assert (
            relay_frame["payload"]["message"]["created_at"]
            == created_message.json()["created_at"]
        )
        assert relay_frame["payload"]["metadata"] == {
            "conversation_type": "direct",
            "mentioned_agent_ids": [],
            "config_profile_version": 1,
        }
        relay_task = app.state.connection.execute(
            "SELECT target_node_id FROM relay_tasks WHERE relay_task_id = ?",
            (relay_frame["payload"]["relay_task_id"],),
        ).fetchone()
        assert relay_task is not None
        assert relay_task["target_node_id"] == "node-1"


def test_create_agent_without_workspace_persists_managed_default_workspace_root(
    tmp_path: Path,
) -> None:
    """Persist the managed default workspace so later session refreshes can trust profile rows."""
    app = create_app(db_path=tmp_path / "im.db")
    with TestClient(app) as client:
        users = UserRepository(app.state.connection)
        owner = register_user(client, username="owner", display_name="Owner")
        authorize(client, owner)
        agent_user = users.create_user(
            username="agent:agent-default", display_name="Agent Default"
        )
        NodeRepository(app.state.connection).upsert_node(
            node_id="node-1", node_name="MacBook"
        )

        async def fake_request_agent_create(
            *,
            target_node_id: str,
            payload: dict[str, object],
            timeout_seconds: float = 5.0,
        ):
            del timeout_seconds
            assert target_node_id == "node-1"
            return {
                "agent_id": payload["agent_id"],
                "display_name": payload["display_name"],
                "description": payload["description"],
                "system_prompt": payload["system_prompt"],
                "skills": payload["skills"],
                "tool_allowlist": payload["tool_allowlist"],
                "group_reply_policy": payload["group_reply_policy"],
                "default_model": payload["default_model"],
                "workspace_root": managed_workspace_root(str(payload["agent_id"])),
            }

        app.state.gateway_handler.request_agent_create = fake_request_agent_create

        created = client.post(
            "/im/v1/nodes/node-1/agents",
            json={
                "agent_id": agent_user.id,
                "owner_id": owner.owner_id,
                "display_name": "Agent Default",
                "description": "managed workspace",
                "system_prompt": "You are Agent Default.",
                "skills": ["plan"],
                "tool_allowlist": ["read"],
                "group_reply_policy": "MENTION",
                "default_model": "claude-sonnet-4",
            },
        )
        assert created.status_code == 201
        assert created.json()["workspace_is_default"] is True
        assert created.json()["workspace_root"].endswith(
            f"/nano-assistant/workspace/{agent_user.id}"
        )

        row = app.state.connection.execute(
            "SELECT workspace_root FROM agent_profiles WHERE agent_id = ?",
            (agent_user.id,),
        ).fetchone()
        assert row is not None
        assert row["workspace_root"].endswith(
            f"/nano-assistant/workspace/{agent_user.id}"
        )


def test_create_agent_pushes_config_sync_to_connected_gateway(tmp_path: Path) -> None:
    """Notify a connected bound node immediately when a new agent is created."""
    app = create_app(db_path=tmp_path / "im.db")
    with TestClient(app) as client:
        users = UserRepository(app.state.connection)
        owner = register_user(client, username="owner", display_name="Owner")
        authorize(client, owner)
        agent_user = users.create_user(
            username="agent:agent-live", display_name="Agent Live"
        )
        NodeRepository(app.state.connection).upsert_node(
            node_id="node-1", node_name="MacBook"
        )

        with client.websocket_connect("/im/ws/gateway") as websocket:
            websocket.send_json(
                {
                    "type": "node.register",
                    "payload": {
                        "node_id": "node-1",
                        "node_name": "MacBook",
                        "version": "1.0.0",
                        "agents": [agent_user.id],
                        "capabilities": {"relay": True},
                    },
                }
            )
            assert websocket.receive_json()["type"] == "ack"

            creation_result: dict[str, object] = {}

            def _create_agent() -> None:
                creation_result["response"] = client.post(
                    "/im/v1/nodes/node-1/agents",
                    json={
                        "agent_id": agent_user.id,
                        "owner_id": owner.owner_id,
                        "display_name": "Agent Live",
                        "description": "runtime-created helper",
                        "system_prompt": "You are Agent Live.",
                        "skills": ["plan"],
                        "tool_allowlist": ["read"],
                        "group_reply_policy": "MENTION",
                        "default_model": "claude-sonnet-4",
                    },
                )

            creation_worker = threading.Thread(target=_create_agent)
            creation_worker.start()
            create_request = websocket.receive_json()
            assert create_request["type"] == "agent.create"
            request_id = create_request["payload"]["request_id"]
            websocket.send_json(
                {
                    "type": "agent.created",
                    "payload": {
                        "request_id": request_id,
                        "node_id": "node-1",
                        "agent": {
                            "agent_id": agent_user.id,
                            "display_name": "Agent Live",
                            "description": "runtime-created helper",
                            "system_prompt": "You are Agent Live.",
                            "skills": ["plan"],
                            "tool_allowlist": ["read"],
                            "group_reply_policy": "MENTION",
                            "default_model": "claude-sonnet-4",
                            "workspace_root": _WORKSPACE_PATH_SETTING,
                        },
                    },
                }
            )

            assert websocket.receive_json() == {
                "type": "ack",
                "payload": {
                    "message_type": "agent.created",
                    "request_id": request_id,
                    "node_id": "node-1",
                },
            }
            assert websocket.receive_json() == {
                "type": "config.sync",
                "payload": {"agent_id": agent_user.id, "profile_version": 1},
            }
            creation_worker.join(timeout=5)
            created = creation_result["response"]
            assert created.status_code == 201
