"""Compatibility shim re-exporting canonical core hook type declarations."""

from nano_multiagent.core.hooks.types import (
    ALL_HOOK_EVENTS,
    DEFAULT_HOOK_PRIORITY,
    DEFAULT_HOOK_TIMEOUT_MS,
    INTERCEPT_EVENTS,
    OBSERVE_EVENTS,
    HookEventMode,
    HookEventName,
    HookEventType,
    HookHandler,
    HookPayload,
    HookRegistration,
    HookResult,
    HookSource,
    HookStatus,
    InputHookAction,
    LoadedHookModule,
    ensure_known_hook_event,
    event_mode_of,
    normalize_hook_event,
)

__all__ = [
    "ALL_HOOK_EVENTS",
    "DEFAULT_HOOK_PRIORITY",
    "DEFAULT_HOOK_TIMEOUT_MS",
    "INTERCEPT_EVENTS",
    "OBSERVE_EVENTS",
    "HookEventMode",
    "HookEventName",
    "HookEventType",
    "HookHandler",
    "HookPayload",
    "HookRegistration",
    "HookResult",
    "HookSource",
    "HookStatus",
    "InputHookAction",
    "LoadedHookModule",
    "ensure_known_hook_event",
    "event_mode_of",
    "normalize_hook_event",
]
